apiVersion: apps/v1
kind: Deployment
metadata:
  name: python
  labels:
    app: python
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python
  strategy:
    type: Recreate   
  template:
    metadata:
      labels:
        app: python
    spec:
      containers:
      - image: group1:0.0.1
        imagePullPolicy: Never 
        name: python
        
        ports:
        - containerPort: 5000
          name: python
