apiVersion: v1
kind: Service
metadata:
  name: python 
  labels:
    app: python
spec:
  type: NodePort
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 32767 
  selector:
    app: python
